### ISSUE TITLE
[Factorio 2.0.8] Overload doesn't work

### ISSUE THREAD

**Issue by eugenikus8** [wretlaw120/Wretlaw-Beacon-Rebalance#3]
Factorio 2.0.8.
1. If you install several beacons of the same type, the assembler does not turn off, the modules from the beacons simply stop working on it, i.e. overload does not work as intended.
 2. If you install 1 beacon of each type, then they all act on the assembler. Overload doesn't work at all.

**Comment by wretlaw120** [comment]
for 1, the beacons should stop giving benefits to the machine. i changed the overload to a default off setting (so that the punishment for overlapping beacons is less severe)... maybe that was a stupid idea. for 2, i guess i didnt test that, oops. will look into it

**Comment by eugenikus8** [comment]
Previously, if an icon was shown when an overload occurred, now, if the modules stopped working, there is no icon. You may not notice this by accident.
