### ISSUE TITLE
Beacon Rebalance 2.0.1 [ru locale]

### ISSUE THREAD

**Issue by eugenikus8** [wretlaw120/Wretlaw-Beacon-Rebalance#4]
beacon-overload=Машина перегружена
beacon-overload-ended=Снята лишняя нагрузка с маяка

[entity-name]
beacon=Маяк Mk1
wr-beacon-2=Маяк Mk2
wr-beacon-3=Маяк Mk3

[entity-description]
beacon=Распространяет эффекты модуля на ближайшие машины. Использование нескольких маяков на одной машине приведет к ее перегрузке. Этот маяк имеет всего восемь слотов для модулей и малый радиус действия, но он более эффективен, чем маяки Mk2 и Mk3.
wr-beacon-2=Распространяет эффекты модуля на ближайшие машины. Использование нескольких маяков на одной машине приведет к ее перегрузке. Этот маяк имеет пятнадцать слотов для модулей и большую дальность действия, но не так эффективен, как Beacon Mk1.
wr-beacon-3=Распространяет эффекты модуля на ближайшие машины. Использование нескольких маяков на одной машине приведет к ее перегрузке. Этот маяк имеет двадцать слотов для модулей и большой радиус действия, но является наименее эффективным маяком.

[technology-name]

[technology-description]
effect-transmission=Маяки способны передавать эффекты размещенных внутри них модулей улучшения ближайшим дружественным машинам. Однако машина может быть затронута только одним маяком за раз, иначе она будет перегружена. Маяки более высокого уровня имеют больший радиус действия и слоты, но имеют более высокую мощность.

[item-name]
beacon=Маяк Mk1
wr-beacon-2=Маяк Mk2
wr-beacon-3=Маяк Mk3

[mod-setting-name]
wret-overload-enable-beaconmk2=Включить маяк Mk2
wret-overload-enable-beaconmk3=Включить маяк Mk3
wret-overload-enable-notnotmelon-style=Включить альтернативный баланс Маяка Mk1
wret-overload-enable-lamp-tile-detection=Включить лампу отладки
wret-change-K2-beacon=Ребалансировка маяка сингулярности
wret-block-FE-beacons=Удалить маяки FE+
wret-FE-beacons-modification=Ребалансировка маяков FE+
wret-block-bob=Отключить маяки Bob's Modules
wret-change-bob=Перебалансировать маяки Bob's Modules
wret-overload-keep-vanilla-sprite-mk1=Сохранить ванильный спрайт для Маяк MK1
wret-overload-disable-overloaded=Перегрузка заводов, на которые действует несколько маяков

[mod-setting-description]
wret-overload-enable-beaconmk2=Если снять этот флажок, маяк Mk2 будет удален (если включен маяк Mk3, ничего не произойдет).
wret-overload-enable-beaconmk3=Если снять этот флажок, маяк Mk3 будет удален.
wret-overload-enable-notnotmelon-style=Увеличивает дальность действия маяка Mk1 до девяти тайлов, а количество слотов для модулей — до четырех.
wret-overload-enable-lamp-tile-detection=Установка ламп показывает игроку количество маяков, влияющих на тайл под ними, и какие именно маяки это делают. (Если устанавливать лампы слишком быстро, значение не отобразится в чате).
wret-change-K2-beacon=Дает Маяку Сингулярности 15 слотов для модулей.
wret-block-FE-beacons=Удаляет маяки FE+, если вам нужны только модули из этого мода.
wret-FE-beacons-modification=Дает FE+ маяку mk3 12 слотов и FE+ маяку mk2 10 слотов (имеет значение только в том случае, если вы включаете маяки из этого мода).
wret-block-bob=Удаляет маяки Bob's Modules, если вы предпочитаете использовать только Rebalance's beacons.
wret-change-bob=Изменяет маяки Bob's Modules в соответствии с темой Rebalances.
wret-overload-disable-overloaded=Если не отмечено, заводы не будут отключаться, просто маяки перестанут оказывать какое-либо влияние.

[mod-name]
wret-beacon-rebalance-mod=Beacon Rebalance - Ребаланс маяков

[mod-description]
wret-beacon-rebalance-mod=Мод ребалансировки маяков, который имитирует баланс маяков Space Exploration с дополнительной механикой перегрузки.

**Comment by wretlaw120** [comment]
added in 2.0.2
