### ISSUE TITLE
[Crash] wret-beacon-rebalance-mod_2.0.1

### ISSUE THREAD

**Issue by eugenikus8** [wretlaw120/Wretlaw-Beacon-Rebalance#5]
In EditorExtensions testing mode, an error appears when installing "captive-biter-spawner"

Addition. The same error occurs when installing a miner's depot from the Mining Drones by Klonan and Mining Drones 2.0 Remastered by AivanF

![2024-10-24_102454](https://github.com/user-attachments/assets/a706984e-f5de-486b-b594-d20a9fb13a8c)

**Comment by wretlaw120** [comment]
fixed in next release
